name: React build
on:
  push:
    branches:
      - main

jobs:
  SSH:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18.x
      - name: SSH-deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.REMOTE_IP }}
          username: ubuntu
          key: ${{ secrets.SSH_PEM_KEY }}
          port: 22
          script: |
            cd animal-FrontEnd/
            sudo git pull origin main
            sudo yarn install
            sudo yarn build
            ls -al
            sudo service nginx restart
