##name: React build
##on:
##  push:
##    branches:
##      - main
##
##jobs:
##  SSH:
##    runs-on: ubuntu-latest
##    steps:
##      - uses: actions/checkout@v3
##      - uses: actions/setup-node@v3
##        with:
##          node-version: 18.16.0
##      - name: SSH-deploy
##        uses: appleboy/ssh-action@master
##        with:
##          host: ${{ secrets.REMOTE_IP }} # SSH 접속용 IP
##          username: ubuntu
##          key: ${{ secrets.SSH_PEM_KEY }} # SSH 접속용 키
##          port: 22 # SSH 접속용 포트
##          script: |
##            ls -al
##            sudo su
##            cd animal-FrontEnd/
##      - name: git pull origin main
##        run: |
##          git pull
##          rm -rf node_modules
##          yarn install
##      - name: yarn build
##        env:
##          CI: false
##        run: yarn build
##      - name: service start
##        env:
##          CI: false
##        run: sudo service nginx restart
#name: React build
#on:
#  push:
#    branches:
#      - main
#
#jobs:
#  SSH:
#    runs-on: ubuntu-latest
#    steps:
#      - uses: actions/checkout@v3
#      - uses: actions/setup-node@v3
#        with:
#          node-version: 18.16.0
#      - name: Install dependencies and build
#        run: |
#          npm ci
#          npm run build
#      - name: Copy files to remote server
#        run: scp -r ./build ubuntu@${{ secrets.REMOTE_IP }}:/home/ubuntu/animal-FrontEnd/
#      - name: SSH-deploy
#        uses: appleboy/ssh-action@master
#        with:
#          host: ${{ secrets.REMOTE_IP }}
#          username: ubuntu
#          key: ${{ secrets.SSH_PEM_KEY }}
#          port: 22
#          script: |
#            ls -al
#            sudo su
#            cd animal-FrontEnd/
#            sudo service nginx restart
#name: React build
#on:
#  push:
#    branches:
#      - main
#
#jobs:
#  SSH:
#    runs-on: ubuntu-latest
#    steps:
#      - uses: actions/checkout@v3
#      - uses: actions/setup-node@v3
#        with:
#          node-version: 18.16.0
#      - name: SSH-deploy
#        uses: appleboy/ssh-action@master
#        with:
#          host: ${{ secrets.REMOTE_IP }}
#          username: ubuntu
#          key: ${{ secrets.SSH_PEM_KEY }}
#          port: 22
#          script: |
#            cd animal-FrontEnd/
#            sudo git pull origin main
#            yarn install --frozen-lockfile
#            yarn build
#            ls -al
#            sudo service nginx restart
name: React build
on:
  push:
    branches:
      - main

jobs:
  SSH:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18.16.0
      - name: Install dependencies and build
        run: |
          cd animal-FrontEnd/
          yarn install --frozen-lockfile
          yarn build
      - name: SSH-deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.REMOTE_IP }}
          username: ubuntu
          key: ${{ secrets.SSH_PEM_KEY }}
          port: 22
          script: |
            cd animal-FrontEnd/
            sudo git pull origin main
            ls -al
            sudo service nginx restart
