name: React build
on:
  push:
    branches:
      - main

jobs:
  SSH:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18.16.0
      - name: SSH-deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.REMOTE_IP }} # SSH 접속용 IP
          username: ubuntu
          key: ${{ secrets.SSH_PEM_KEY }} # SSH 접속용 키
          port: 22 # SSH 접속용 포트
          script: |
            ls -al
            sudo su 
            cd animal-FrontEnd/
            sudo chmod 755 .git
      - name: Build
        run: |
          git pull origin main
          sudo npm install
          sudo npm run build
          sudo service nginx restart
