name: React build
on:
  push:
    branches:
      - main

jobs:
  SSH:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: SSH-deploy

        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.REMOTE_IP }} # ssh 접속용 ip
          username: ubuntu
          key: ${{ secrets.SSH_PEM_KEY }} # ssh 접속용 password
          port: 22 # ssh 접속용 port
          script: |
           ls -al
           sudo su 
           cd animal-FrontEnd/
           sudo chmod 755 .git
           sudo git pull origin main
           sudo yarn run build
           sudo service nginx restart

            
           
            
           
